from pydantic import BaseModel, Field


class JobRequest(BaseModel):
    prompt: str = Field(..., min_length=2, description="The user's prompt for analysis.")
    session_id: str = Field(..., description="UUID generated by the frontend for this chat session.")

class JobStatus(BaseModel):
    job_id: str
    status: str

class ReportResponse(BaseModel):
    job_id: str
    status: str
    report: str | None = None
